apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-http
  labels:
    app: {{ $.Release.Name }}
spec:
  type: ClusterIP
  ports:
    - port: {{ include "func.string.appPort" $ }}
      targetPort: {{ include "func.string.nginxPort" $ }}
      protocol: TCP
      name: http
  selector:
    app: {{ $.Release.Name }}
    podServe: http
