name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build PHP FPM image
        run: |
          docker build --progress=plain --no-cache -t lapsatech/swimmingtools-php-fpm:latest ./src/docker-php-fpm
      - name: Build NGINX image
        run: |
          docker build --progress=plain --no-cache -t lapsatech/swimmingtools-nginx:latest   ./src/docker-nginx
      - name: Push images
        run: |
          if [ "${GITHUB_REF#refs/heads/}" = "master" ]
          then
            push lapsatech/swimmingtools-php-fpm:latest || exit $?
            push lapsatech/swimmingtools-php-nginx:latest || exit $?
          fi
