name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-images:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      if: ${{ github.ref == 'refs/heads/master' }}
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build lapsatech/swimmingtools-php-fpm image
      uses: docker/build-push-action@v4
      with:
        context: ./src/docker-php-fpm
        push: ${{ github.ref == 'refs/heads/master' }}
        tags: lapsatech/swimmingtools-nginx:latest
    - name: Build lapsatech/swimmingtools-php-fpm image
      uses: docker/build-push-action@v4
      with:
        context: ./src/docker-nginx
        push: ${{ github.ref == 'refs/heads/master' }}
        tags: lapsatech/swimmingtools-nginx:latest
